-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TRIGGER data_update_trigger
-- AFTER INSERT OR UPDATE ON logs
-- FOR EACH ROW
-- EXECUTE FUNCTION notify_update();
